config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#home"
  get "about" => "pages#about"
  get "snickers" => "pages#snickers"
  get "veggie" => "pages#veggie"
  get "meat" => "pages#meat"
  get "vegan" => "pages#vegan"
  get "pizzas" => "pages#pizzas"
  get "spices" => "pages#spices"
  get "burgers" => "pages#burgers"
  get "mexicanburger" => "pages#mexicanburger"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def snickers
  end

  def veggie
  end

  def meat
  end

  def vegan
  end

  def pizzas
  end

  def spices
  end

  def burgers
  end

  def mexicanburger
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Meat A Tarian", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
        <li><%= link_to "|Home|",root_path %></li>
        <li><%= link_to "|About|",about_path %></li>
        <li><%= link_to "|Vegan|",vegan_path %></li>
        <li><%= link_to "|Veggie|",veggie_path %></li>
        <li><%= link_to "|Meat|",meat_path %></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out",destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log In",new_user_session_path %></li>
          <li><%= link_to "Sign Up",new_user_registration_path %></li>
        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meatatarian</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
		<% end %>
		<%= yield %>
    <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2016 Meatatarian Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
    </footer>
	</div>

  

</body>
</html>

app/views/pages/burgers.html.erb
<div class="container marketing">

      <div class="recipe">
        <div class="row">
          <div class="col-sm-4">
            <img class="img-thumbnail" width="400" height="300" <%= image_tag("mexiburger.jpg", :alt => "mexican burger") %>
            <h2>Mexican Tortilla Burger</h2>
            <p><a class="btn btn-default btn-success" <%= link_to "View Recipe",mexicanburger_path %>
          </div>

          <div class="col-sm-4">
            <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "Burger 2") %>  
            <h2>Burger2</h2>
            <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",veggie_path %>
          </div>

          <div class="col-sm-4">
            <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "Burger 3") %> 
            <h2>Burger3</h2>
            <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",meat_path %>
          </div>
        </div>

     

        <div class="row">
              <div class="col-sm-4">
                <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "Burger 4") %>
                <h2>Burger4</h2>
                <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",vegan_path %>
              </div>

              <div class="col-sm-4">
                <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "burger5") %>  
                <h2>Burger5</h2> 
                <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",veggie_path %>
              </div>
        </div>
      </div>
</div>        

app/views/pages/home.html.erb
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <%= image_tag("snickers_1.jpg", :alt => "slide1") %>
          <div class="container">
            <div class="carousel-caption">
              <h3>The Best Ever Raw Vegan snickers</h3>
              <p><a class="btn btn-xs btn-info" <%= link_to "See Recipe",snickers_path %> 
            </div>
          </div>
        </div>
        <div class="item">
          <%= image_tag("snickers.jpg", :alt => "slide2") %>
          <div class="container">
            <div class="carousel-caption">

              <h3></h3>
              
              <p><a class="btn btn-xs btn-info" <%= link_to "See Recipe",snickers_path %> 
            </div>
          </div>
        </div>
        <div class="item">
          <%= image_tag("snickers_2.jpg", :alt => "slide3") %>
            <div class="carousel-caption">

              <h3></h3>
             
              <p><a class="btn btn-xs btn-info" <%= link_to "See Recipe",snickers_path %>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><br><br><br><br><!-- /.carousel -->

  <hr class="featurette-divider">
  <div class="container marketing">

      <!-- Three columns of text below the carousel -->
        <div class="row">
          <div class="col-sm-4">
            <img class="img-thumbnail" width="140" height="140" <%= image_tag("veganthumb.jpg", :alt=> "vegan") %>
            <h2>Vegans</h2>
            <p>Explore the full list of Vegan recipes</p>
            <p><a class="btn btn-default btn-warning" <%= link_to "View Recipes",vegan_path %> 
          </div>

          <div class="col-sm-4">
            <img class="img-thumbnail" width="140" height="140" <%= image_tag("veggiethumb.jpg", :alt => "veggie") %>  
            <h2>Veggies</h2>
            <p>Explore the full list of Vegetarian recipes</p>
            <p><a class="btn btn-default btn-warning" <%= link_to "View Recipes",veggie_path %>
          </div>

          <div class="col-sm-4">
            <img class="img-thumbnail" width="140" height="140" <%= image_tag("meat.jpg", :alt => "meat") %> 
            <h2>Meat Eaters</h2>
            <p>Explore the full list of Meat recipes</p>
            <p><a class="btn btn-default btn-warning" <%= link_to "View Recipes",meat_path %>
          </div>
        </div>
    </div> 

    <hr class="featurette-divider">
     <div class="container">
      <section>
        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading"><u><b>Pizza Insolito</b></u></h2>
            <p class="lead">If you're anything like me then unfortunately, pizza is a big part of your diet. But even pizza can be boring when most takeaways have the same or at least very similar toppings. This is what inspired us to create these unique and unusual pizzas! Hope you enjoy... <p><a class="btn btn-info" <%= link_to "View Pizzas",pizzas_path %>
          </div>
          <div class="col-md-5">
            <img class="image-square img-responsive center-block" width="350" height="350" <%= image_tag("pizza.jpg", style: "border: 5px solid white", :alt => "pizza") %>
          </div>
        </div>
      </section>
      

      <hr class="featurette-divider">
      <section>
        <div class="row featurette">
          <div class="col-md-7 col-md-push-5">
            <h2 class="featurette-heading"><u><b>Beefburger 5 Ways</b></u></h2>
            <p class="lead">Nowadays you can get anything on a burger, Pulled pork, bacon, egg... But I wanted to create a variety of burgers that puts the emphasis back on the <b>beef</b> burger. <p><a class="btn btn-info" <%= link_to "View Burgers",burgers_path %>
          </div>

          <div class="col-md-5 col-md-pull-7">
            <img class="image-square img-responsive center-block" width="350" height="350" <%= image_tag("mexiburger.jpg", style: "border: 5px solid white", :alt => "mexi burger") %>
          </div>
      </section>

      <hr class="featurette-divider">
      <section>
        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading"><u><b>Essential Spices</b></u></h2>
            <p class="lead">Have you ever wondered where paprika came from or what exactly curry powder is made of? In vegan and vegetarian cooking spices become even more important as you lose the natural meat flavourings. Here we have put together a list of your every day spices along with some more unusual spices to give you an idea of how to use them and also which spices mix well together. <p><a class="btn btn-info" <%= link_to "Explore Spices",spices_path %>
          </div>
          <div class="col-md-5">
            <img class="image-square img-responsive center-block" width="350" height="350" <%= image_tag("spice.jpg", style: "border: 5px solid white", :alt => "spice") %>
          </div>
        </div>
      </section>

      

app/views/pages/meat.html.erb
<div class="container marketing">

      <div class="recipe">
        <div class="row">
          <div class="col-sm-4">
            <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "snickers") %>
            <h2>Recipe2</h2>
            <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",snickers_path %>
          </div>

          <div class="col-sm-4">
            <img class="img-thumbnail" width="400" height="300" <%= image_tag("mexiburger.jpg", :alt => "Burger 2") %>  
            <h2>Mexican Tortilla Burger</h2>
            <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",mexicanburger_path %>
          </div>

          <div class="col-sm-4">
            <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "Burger 3") %> 
            <h2>Recipe3</h2>
            <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",meat_path %>
          </div>
        </div>

     

        <div class="row">
              <div class="col-sm-4">
                <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "Burger 4") %>
                <h2>recipe4</h2>
                <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",vegan_path %>
              </div>

              <div class="col-sm-4">
                <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "burger5") %>  
                <h2>Recipe5</h2> 
                <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",veggie_path %>
              </div>

              <div class="col-sm-4">
                <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "burger5") %>  
                <h2>Recipe6</h2> 
                <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",veggie_path %>
              </div>
        </div>
      </div>
</div>  

app/views/pages/mexicanburger.html.erb
<h1>Mexican Burger</h1>

app/views/pages/pizzas.html.erb
<div class="container marketing">

      <div class="recipe">
        <div class="row">
          <div class="col-sm-4">
            <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "snickers") %>
            <h2>Recipe1</h2>
            <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",snickers_path %>
          </div>

          <div class="col-sm-4">
            <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "Burger 2") %>  
            <h2>Recipe2</h2>
            <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",veggie_path %>
          </div>

          <div class="col-sm-4">
            <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "Burger 3") %> 
            <h2>Recipe3</h2>
            <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",meat_path %>
          </div>
        </div>

     

        <div class="row">
              <div class="col-sm-4">
                <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "Burger 4") %>
                <h2>recipe4</h2>
                <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",vegan_path %>
              </div>

              <div class="col-sm-4">
                <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "burger5") %>  
                <h2>Recipe5</h2> 
                <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",veggie_path %>
              </div>

              <div class="col-sm-4">
                <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "burger5") %>  
                <h2>Recipe6</h2> 
                <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",veggie_path %>
              </div>
        </div>
      </div>
</div>  

app/views/pages/snickers.html.erb
<div class="container">
 <div class="snickers">
  <div class="col-md-8">
   <h2><b>Raw Vegan Snickers</b></h2>
   <%= image_tag("snickers_1.jpg", :alt => "snikers recipe") %>
  </div>

  <div class="col-md-4">
  	<h3><b><u>Ingredients</u></b></h3><br>
  	<ul type="circle">
	  <div class="lead"><li>Cashews 200G</li><br>
		  <li>Dates 1/2 Cup </li><br>
		  <li>Agave Nectar 1tbs</li><br>
		  <li>Peanuts 75G</li><br>
		  <li>Cacao Powder 1/4 Cup</li><br>
		  <li>Cacao butter 50G</li><br>
		  <li>Sea Salt 1/2 tsp</li><br>
	  </div>
	</ul>
  </div>
 </div>
</div>

app/views/pages/vegan.html.erb
<div class="container marketing">

      <div class="recipe">
        <div class="row">
          <div class="col-sm-4">
            <img class="img-thumbnail" width="400" height="300" <%= image_tag("snickers.jpg", :alt => "snickers") %>
            <h2>The Best Ever Raw Vegan Snickers</h2>
            <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",snickers_path %>
          </div>

          <div class="col-sm-4">
            <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "Burger 2") %>  
            <h2>Recipe2</h2>
            <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",veggie_path %>
          </div>

          <div class="col-sm-4">
            <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "Burger 3") %> 
            <h2>Recipe3</h2>
            <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",meat_path %>
          </div>
        </div>

     

        <div class="row">
              <div class="col-sm-4">
                <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "Burger 4") %>
                <h2>recipe4</h2>
                <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",vegan_path %>
              </div>

              <div class="col-sm-4">
                <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "burger5") %>  
                <h2>Recipe5</h2> 
                <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",veggie_path %>
              </div>

              <div class="col-sm-4">
                <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "burger5") %>  
                <h2>Recipe6</h2> 
                <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",veggie_path %>
              </div>
        </div>
      </div>
</div>  

app/views/pages/veggie.html.erb
<div class="container marketing">

      <div class="recipe">
        <div class="row">
          <div class="col-sm-4">
            <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "snickers") %>
            <h2>Recipe2</h2>
            <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",snickers_path %>
          </div>

          <div class="col-sm-4">
            <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "Burger 2") %>  
            <h2>Recipe2</h2>
            <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",veggie_path %>
          </div>

          <div class="col-sm-4">
            <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "Burger 3") %> 
            <h2>Recipe3</h2>
            <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",meat_path %>
          </div>
        </div>

     

        <div class="row">
              <div class="col-sm-4">
                <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "Burger 4") %>
                <h2>recipe4</h2>
                <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",vegan_path %>
              </div>

              <div class="col-sm-4">
                <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "burger5") %>  
                <h2>Recipe5</h2> 
                <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",veggie_path %>
              </div>

              <div class="col-sm-4">
                <img class="img-thumbnail" width="400" height="300" <%= image_tag("noimage.jpg", :alt => "burger5") %>  
                <h2>Recipe6</h2> 
                <p><a class="btn btn-default btn-success" <%= link_to "View Recipes",veggie_path %>
              </div>
        </div>
      </div>
</div> 